export const NATIONALITIES = [
  { name: "Afghan", value: "AF" },
  { name: "Albanian", value: "AL" },
  { name: "Algerian", value: "DZ" },
  { name: "Andorran", value: "AD" },
  { name: "Angolan", value: "AO" },
  { name: "Antiguans", value: "AG" },
  { name: "Argentinian", value: "AR" },
  { name: "Armenian", value: "AM" },
  { name: "Australian", value: "AU" },
  { name: "Austrian", value: "AT" },
  { name: "Azerbaijani", value: "AZ" },
  { name: "Bahamian", value: "BS" },
  { name: "Bahraini", value: "BH" },
  { name: "Bangladeshi", value: "BD" },
  { name: "Barbadian", value: "BB" },
  { name: "Belarusian", value: "BY" },
  { name: "Belgian", value: "BE" },
  { name: "Belizean", value: "BZ" },
  { name: "Beninese", value: "BJ" },
  { name: "Bhutanese", value: "BT" },
  { name: "Bolivian", value: "BO" },
  { name: "Bosnian", value: "BA" },
  { name: "Brazilian", value: "BR" },
  { name: "British", value: "GB" },
  { name: "Bruneian", value: "BN" },
  { name: "Bulgarian", value: "BG" },
  { name: "Burkinabe", value: "BF" },
  { name: "Burmese", value: "MM" },
  { name: "Burundian", value: "BI" },
  { name: "Cambodian", value: "KH" },
  { name: "Cameroonian", value: "CM" },
  { name: "Canadian", value: "CA" },
  { name: "Cape Verdean", value: "CV" },
  { name: "Central African", value: "CF" },
  { name: "Chadian", value: "TD" },
  { name: "Chilean", value: "CL" },
  { name: "Chinese", value: "CN" },
  { name: "Colombian", value: "CO" },
  { name: "Comoran", value: "KM" },
  { name: "Congolese", value: "CG" },
  { name: "Costa Rican", value: "CR" },
  { name: "Croatian", value: "HR" },
  { name: "Cuban", value: "CU" },
  { name: "Cypriot", value: "CY" },
  { name: "Czech", value: "CZ" },
  { name: "Danish", value: "DK" },
  { name: "Djibouti", value: "DJ" },
  { name: "Dominican", value: "DO" },
  { name: "Dutch", value: "NL" },
  { name: "East Timorese", value: "TL" },
  { name: "Ecuadorean", value: "EC" },
  { name: "Egyptian", value: "EG" },
  { name: "Emirian", value: "AE" },
  { name: "Equatorial Guinean", value: "GQ" },
  { name: "Eritrean", value: "ER" },
  { name: "Estonian", value: "EE" },
  { name: "Ethiopian", value: "ET" },
  { name: "Fijian", value: "FJ" },
  { name: "Filipino", value: "PH" },
  { name: "Finnish", value: "FI" },
  { name: "French", value: "FR" },
  { name: "Gabonese", value: "GA" },
  { name: "Gambian", value: "GM" },
  { name: "Georgian", value: "GE" },
  { name: "German", value: "DE" },
  { name: "Ghanaian", value: "GH" },
  { name: "Greek", value: "GR" },
  { name: "Grenadian", value: "GD" },
  { name: "Guatemalan", value: "GT" },
  { name: "Guinea-Bissauan", value: "GW" },
  { name: "Guinean", value: "GN" },
  { name: "Guyanese", value: "GY" },
  { name: "Haitian", value: "HT" },
  { name: "Herzegovinian", value: "BA" },
  { name: "Honduran", value: "HN" },
  { name: "Hungarian", value: "HU" },
  { name: "I-Kiribati", value: "KI" },
  { name: "Icelander", value: "IS" },
  { name: "Indian", value: "IN" },
  { name: "Indonesian", value: "ID" },
  { name: "Iranian", value: "IR" },
  { name: "Iraqi", value: "IQ" },
  { name: "Irish", value: "IE" },
  { name: "Israeli", value: "IL" },
  { name: "Italian", value: "IT" },
  { name: "Ivorian", value: "CI" },
  { name: "Jamaican", value: "JM" },
  { name: "Japanese", value: "JP" },
  { name: "Jordanian", value: "JO" },
  { name: "Kazakhstani", value: "KZ" },
  { name: "Kenyan", value: "KE" },
  { name: "Kittian and Nevisian", value: "KN" },
  { name: "Kuwaiti", value: "KW" },
  { name: "Kyrgyz", value: "KG" },
  { name: "Laotian", value: "LA" },
  { name: "Latvian", value: "LV" },
  { name: "Lebanese", value: "LB" },
  { name: "Liberian", value: "LR" },
  { name: "Libyan", value: "LY" },
  { name: "Liechtensteiner", value: "LI" },
  { name: "Lithuanian", value: "LT" },
  { name: "Luxembourger", value: "LU" },
  { name: "Macedonian", value: "MK" },
  { name: "Malagasy", value: "MG" },
  { name: "Malawian", value: "MW" },
  { name: "Malaysian", value: "MY" },
  { name: "Maldivan", value: "MV" },
  { name: "Malian", value: "ML" },
  { name: "Maltese", value: "MT" },
  { name: "Marshallese", value: "MH" },
  { name: "Mauritanian", value: "MR" },
  { name: "Mauritian", value: "MU" },
  { name: "Mexican", value: "MX" },
  { name: "Micronesian", value: "FM" },
  { name: "Moldovan", value: "MD" },
  { name: "Monacan", value: "MC" },
  { name: "Mongolian", value: "MN" },
  { name: "Moroccan", value: "MA" },
  { name: "Mosotho", value: "LS" },
  { name: "Motswana", value: "BW" },
  { name: "Mozambican", value: "MZ" },
  { name: "Namibian", value: "NA" },
  { name: "Nauruan", value: "NR" },
  { name: "Nepalese", value: "NP" },
  { name: "New Zealander", value: "NZ" },
  { name: "Nicaraguan", value: "NI" },
  { name: "Nigerian", value: "NG" },
  { name: "Nigerien", value: "NE" },
  { name: "North Korean", value: "KP" },
  { name: "Northern Irish", value: "GB" },
  { name: "Norwegian", value: "NO" },
  { name: "Omani", value: "OM" },
  { name: "Pakistani", value: "PK" },
  { name: "Palauan", value: "PW" },
  { name: "Panamanian", value: "PA" },
  { name: "Papua New Guinean", value: "PG" },
  { name: "Paraguayan", value: "PY" },
  { name: "Peruvian", value: "PE" },
  { name: "Polish", value: "PL" },
  { name: "Portuguese", value: "PT" },
  { name: "Qatari", value: "QA" },
  { name: "Romanian", value: "RO" },
  { name: "Russian", value: "RU" },
  { name: "Rwandan", value: "RW" },
  { name: "Saint Lucian", value: "LC" },
  { name: "Salvadoran", value: "SV" },
  { name: "Samoan", value: "WS" },
  { name: "San Marinese", value: "SM" },
  { name: "Sao Tomean", value: "ST" },
  { name: "Saudi", value: "SA" },
  { name: "Scottish", value: "GB" },
  { name: "Senegalese", value: "SN" },
  { name: "Serbian", value: "RS" },
  { name: "Seychellois", value: "SC" },
  { name: "Sierra Leonean", value: "SL" },
  { name: "Singaporean", value: "SG" },
  { name: "Slovakian", value: "SK" },
  { name: "Slovenian", value: "SI" },
  { name: "Solomon Islander", value: "SB" },
  { name: "Somali", value: "SO" },
  { name: "South African", value: "ZA" },
  { name: "South Korean", value: "KR" },
  { name: "Spanish", value: "ES" },
  { name: "Sri Lankan", value: "LK" },
  { name: "Sudanese", value: "SD" },
  { name: "Surinamer", value: "SR" },
  { name: "Swazi", value: "SZ" },
  { name: "Swedish", value: "SE" },
  { name: "Swiss", value: "CH" },
  { name: "Syrian", value: "SY" },
  { name: "Taiwanese", value: "TW" },
  { name: "Tajik", value: "TJ" },
  { name: "Tanzanian", value: "TZ" },
  { name: "Thai", value: "TH" },
  { name: "Togolese", value: "TG" },
  { name: "Tongan", value: "TO" },
  { name: "Trinidadian or Tobagonian", value: "TT" },
  { name: "Tunisian", value: "TN" },
  { name: "Turkish", value: "TR" },
  { name: "Tuvaluan", value: "TV" },
  { name: "Ugandan", value: "UG" },
  { name: "Ukrainian", value: "UA" },
  { name: "Uruguayan", value: "UY" },
  { name: "Uzbekistani", value: "UZ" },
  { name: "Venezuelan", value: "VE" },
  { name: "Vietnamese", value: "VN" },
  { name: "Welsh", value: "GB" },
  { name: "Yemenite", value: "YE" },
  { name: "Zambian", value: "ZM" },
  { name: "Zimbabwean", value: "ZW" },
];
